// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransactionPO.proto

package com.bjs.contract.proto.transaction;

public final class TransactionPOProto {
  private TransactionPOProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transaction_TransactionPO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transaction_TransactionPO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023TransactionPO.proto\022\013transaction\032\037goog" +
      "le/protobuf/timestamp.proto\032\036google/prot" +
      "obuf/wrappers.proto\"\220\004\n\rTransactionPO\022\'\n" +
      "\002id\030\001 \001(\0132\033.google.protobuf.Int64Value\022," +
      "\n\007fromUid\030\002 \001(\0132\033.google.protobuf.Int64V" +
      "alue\022-\n\010fromType\030\003 \001(\0132\033.google.protobuf" +
      ".Int32Value\022\023\n\013fromBalance\030\004 \001(\t\022*\n\005toUi" +
      "d\030\005 \001(\0132\033.google.protobuf.Int64Value\022+\n\006" +
      "toType\030\006 \001(\0132\033.google.protobuf.Int32Valu" +
      "e\022\021\n\ttoBalance\030\007 \001(\t\022\016\n\006amount\030\010 \001(\t\022\014\n\004" +
      "meta\030\t \001(\t\022\r\n\005scene\030\n \001(\t\022\017\n\007refType\030\013 \001" +
      "(\t\022*\n\005refId\030\014 \001(\0132\033.google.protobuf.Int6" +
      "4Value\022*\n\005opUid\030\r \001(\0132\033.google.protobuf." +
      "Int64Value\022\014\n\004opIp\030\016 \001(\t\022)\n\005ctime\030\017 \001(\0132" +
      "\032.google.protobuf.Timestamp\022)\n\005mtime\030\020 \001" +
      "(\0132\032.google.protobuf.TimestampB:\n\"com.bj" +
      "s.contract.proto.transactionB\022Transactio" +
      "nPOProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_transaction_TransactionPO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transaction_TransactionPO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transaction_TransactionPO_descriptor,
        new String[] { "Id", "FromUid", "FromType", "FromBalance", "ToUid", "ToType", "ToBalance", "Amount", "Meta", "Scene", "RefType", "RefId", "OpUid", "OpIp", "Ctime", "Mtime", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
