// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FundingRateService.proto

package com.bjs.contract.proto.fundingRate;

/**
 * Protobuf type {@code fundingRate.FundingRateListReply}
 */
public  final class FundingRateListReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fundingRate.FundingRateListReply)
    FundingRateListReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FundingRateListReply.newBuilder() to construct.
  private FundingRateListReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FundingRateListReply() {
    fundingRatePO_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FundingRateListReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              fundingRatePO_ = new java.util.ArrayList<FundingRatePO>();
              mutable_bitField0_ |= 0x00000001;
            }
            fundingRatePO_.add(
                input.readMessage(FundingRatePO.parser(), extensionRegistry));
            break;
          }
          case 16: {

            total_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        fundingRatePO_ = java.util.Collections.unmodifiableList(fundingRatePO_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return FundingRateBizServiceProto.internal_static_fundingRate_FundingRateListReply_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return FundingRateBizServiceProto.internal_static_fundingRate_FundingRateListReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            FundingRateListReply.class, Builder.class);
  }

  private int bitField0_;
  public static final int FUNDINGRATEPO_FIELD_NUMBER = 1;
  private java.util.List<FundingRatePO> fundingRatePO_;
  /**
   * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
   */
  public java.util.List<FundingRatePO> getFundingRatePOList() {
    return fundingRatePO_;
  }
  /**
   * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
   */
  public java.util.List<? extends FundingRatePOOrBuilder>
      getFundingRatePOOrBuilderList() {
    return fundingRatePO_;
  }
  /**
   * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
   */
  public int getFundingRatePOCount() {
    return fundingRatePO_.size();
  }
  /**
   * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
   */
  public FundingRatePO getFundingRatePO(int index) {
    return fundingRatePO_.get(index);
  }
  /**
   * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
   */
  public FundingRatePOOrBuilder getFundingRatePOOrBuilder(
      int index) {
    return fundingRatePO_.get(index);
  }

  public static final int TOTAL_FIELD_NUMBER = 2;
  private long total_;
  /**
   * <code>int64 total = 2;</code>
   */
  public long getTotal() {
    return total_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < fundingRatePO_.size(); i++) {
      output.writeMessage(1, fundingRatePO_.get(i));
    }
    if (total_ != 0L) {
      output.writeInt64(2, total_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < fundingRatePO_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, fundingRatePO_.get(i));
    }
    if (total_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, total_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof FundingRateListReply)) {
      return super.equals(obj);
    }
    FundingRateListReply other = (FundingRateListReply) obj;

    if (!getFundingRatePOList()
        .equals(other.getFundingRatePOList())) return false;
    if (getTotal()
        != other.getTotal()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFundingRatePOCount() > 0) {
      hash = (37 * hash) + FUNDINGRATEPO_FIELD_NUMBER;
      hash = (53 * hash) + getFundingRatePOList().hashCode();
    }
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotal());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static FundingRateListReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FundingRateListReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FundingRateListReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FundingRateListReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FundingRateListReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FundingRateListReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FundingRateListReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FundingRateListReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static FundingRateListReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static FundingRateListReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static FundingRateListReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FundingRateListReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(FundingRateListReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fundingRate.FundingRateListReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fundingRate.FundingRateListReply)
      FundingRateListReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FundingRateBizServiceProto.internal_static_fundingRate_FundingRateListReply_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FundingRateBizServiceProto.internal_static_fundingRate_FundingRateListReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FundingRateListReply.class, Builder.class);
    }

    // Construct using com.bjs.contract.proto.fundingRate.FundingRateListReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFundingRatePOFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (fundingRatePOBuilder_ == null) {
        fundingRatePO_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        fundingRatePOBuilder_.clear();
      }
      total_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return FundingRateBizServiceProto.internal_static_fundingRate_FundingRateListReply_descriptor;
    }

    @Override
    public FundingRateListReply getDefaultInstanceForType() {
      return FundingRateListReply.getDefaultInstance();
    }

    @Override
    public FundingRateListReply build() {
      FundingRateListReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public FundingRateListReply buildPartial() {
      FundingRateListReply result = new FundingRateListReply(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (fundingRatePOBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          fundingRatePO_ = java.util.Collections.unmodifiableList(fundingRatePO_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.fundingRatePO_ = fundingRatePO_;
      } else {
        result.fundingRatePO_ = fundingRatePOBuilder_.build();
      }
      result.total_ = total_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof FundingRateListReply) {
        return mergeFrom((FundingRateListReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(FundingRateListReply other) {
      if (other == FundingRateListReply.getDefaultInstance()) return this;
      if (fundingRatePOBuilder_ == null) {
        if (!other.fundingRatePO_.isEmpty()) {
          if (fundingRatePO_.isEmpty()) {
            fundingRatePO_ = other.fundingRatePO_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFundingRatePOIsMutable();
            fundingRatePO_.addAll(other.fundingRatePO_);
          }
          onChanged();
        }
      } else {
        if (!other.fundingRatePO_.isEmpty()) {
          if (fundingRatePOBuilder_.isEmpty()) {
            fundingRatePOBuilder_.dispose();
            fundingRatePOBuilder_ = null;
            fundingRatePO_ = other.fundingRatePO_;
            bitField0_ = (bitField0_ & ~0x00000001);
            fundingRatePOBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFundingRatePOFieldBuilder() : null;
          } else {
            fundingRatePOBuilder_.addAllMessages(other.fundingRatePO_);
          }
        }
      }
      if (other.getTotal() != 0L) {
        setTotal(other.getTotal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      FundingRateListReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (FundingRateListReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<FundingRatePO> fundingRatePO_ =
      java.util.Collections.emptyList();
    private void ensureFundingRatePOIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        fundingRatePO_ = new java.util.ArrayList<FundingRatePO>(fundingRatePO_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        FundingRatePO, FundingRatePO.Builder, FundingRatePOOrBuilder> fundingRatePOBuilder_;

    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public java.util.List<FundingRatePO> getFundingRatePOList() {
      if (fundingRatePOBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fundingRatePO_);
      } else {
        return fundingRatePOBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public int getFundingRatePOCount() {
      if (fundingRatePOBuilder_ == null) {
        return fundingRatePO_.size();
      } else {
        return fundingRatePOBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public FundingRatePO getFundingRatePO(int index) {
      if (fundingRatePOBuilder_ == null) {
        return fundingRatePO_.get(index);
      } else {
        return fundingRatePOBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public Builder setFundingRatePO(
        int index, FundingRatePO value) {
      if (fundingRatePOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFundingRatePOIsMutable();
        fundingRatePO_.set(index, value);
        onChanged();
      } else {
        fundingRatePOBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public Builder setFundingRatePO(
        int index, FundingRatePO.Builder builderForValue) {
      if (fundingRatePOBuilder_ == null) {
        ensureFundingRatePOIsMutable();
        fundingRatePO_.set(index, builderForValue.build());
        onChanged();
      } else {
        fundingRatePOBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public Builder addFundingRatePO(FundingRatePO value) {
      if (fundingRatePOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFundingRatePOIsMutable();
        fundingRatePO_.add(value);
        onChanged();
      } else {
        fundingRatePOBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public Builder addFundingRatePO(
        int index, FundingRatePO value) {
      if (fundingRatePOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFundingRatePOIsMutable();
        fundingRatePO_.add(index, value);
        onChanged();
      } else {
        fundingRatePOBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public Builder addFundingRatePO(
        FundingRatePO.Builder builderForValue) {
      if (fundingRatePOBuilder_ == null) {
        ensureFundingRatePOIsMutable();
        fundingRatePO_.add(builderForValue.build());
        onChanged();
      } else {
        fundingRatePOBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public Builder addFundingRatePO(
        int index, FundingRatePO.Builder builderForValue) {
      if (fundingRatePOBuilder_ == null) {
        ensureFundingRatePOIsMutable();
        fundingRatePO_.add(index, builderForValue.build());
        onChanged();
      } else {
        fundingRatePOBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public Builder addAllFundingRatePO(
        Iterable<? extends FundingRatePO> values) {
      if (fundingRatePOBuilder_ == null) {
        ensureFundingRatePOIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fundingRatePO_);
        onChanged();
      } else {
        fundingRatePOBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public Builder clearFundingRatePO() {
      if (fundingRatePOBuilder_ == null) {
        fundingRatePO_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        fundingRatePOBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public Builder removeFundingRatePO(int index) {
      if (fundingRatePOBuilder_ == null) {
        ensureFundingRatePOIsMutable();
        fundingRatePO_.remove(index);
        onChanged();
      } else {
        fundingRatePOBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public FundingRatePO.Builder getFundingRatePOBuilder(
        int index) {
      return getFundingRatePOFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public FundingRatePOOrBuilder getFundingRatePOOrBuilder(
        int index) {
      if (fundingRatePOBuilder_ == null) {
        return fundingRatePO_.get(index);  } else {
        return fundingRatePOBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public java.util.List<? extends FundingRatePOOrBuilder>
         getFundingRatePOOrBuilderList() {
      if (fundingRatePOBuilder_ != null) {
        return fundingRatePOBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fundingRatePO_);
      }
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public FundingRatePO.Builder addFundingRatePOBuilder() {
      return getFundingRatePOFieldBuilder().addBuilder(
          FundingRatePO.getDefaultInstance());
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public FundingRatePO.Builder addFundingRatePOBuilder(
        int index) {
      return getFundingRatePOFieldBuilder().addBuilder(
          index, FundingRatePO.getDefaultInstance());
    }
    /**
     * <code>repeated .fundingRate.FundingRatePO fundingRatePO = 1;</code>
     */
    public java.util.List<FundingRatePO.Builder>
         getFundingRatePOBuilderList() {
      return getFundingRatePOFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        FundingRatePO, FundingRatePO.Builder, FundingRatePOOrBuilder>
        getFundingRatePOFieldBuilder() {
      if (fundingRatePOBuilder_ == null) {
        fundingRatePOBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            FundingRatePO, FundingRatePO.Builder, FundingRatePOOrBuilder>(
                fundingRatePO_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        fundingRatePO_ = null;
      }
      return fundingRatePOBuilder_;
    }

    private long total_ ;
    /**
     * <code>int64 total = 2;</code>
     */
    public long getTotal() {
      return total_;
    }
    /**
     * <code>int64 total = 2;</code>
     */
    public Builder setTotal(long value) {
      
      total_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total = 2;</code>
     */
    public Builder clearTotal() {
      
      total_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fundingRate.FundingRateListReply)
  }

  // @@protoc_insertion_point(class_scope:fundingRate.FundingRateListReply)
  private static final FundingRateListReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new FundingRateListReply();
  }

  public static FundingRateListReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FundingRateListReply>
      PARSER = new com.google.protobuf.AbstractParser<FundingRateListReply>() {
    @Override
    public FundingRateListReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FundingRateListReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FundingRateListReply> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<FundingRateListReply> getParserForType() {
    return PARSER;
  }

  @Override
  public FundingRateListReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

