// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MaintenanceMarginRateService.proto

package com.bjs.contract.proto.maintenanceMarginRate;

/**
 * Protobuf type {@code maintenanceMarginRate.MaintenanceMarginRateListRequest}
 */
public  final class MaintenanceMarginRateListRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:maintenanceMarginRate.MaintenanceMarginRateListRequest)
    MaintenanceMarginRateListRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MaintenanceMarginRateListRequest.newBuilder() to construct.
  private MaintenanceMarginRateListRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MaintenanceMarginRateListRequest() {
    maintenanceMarginRatePO_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MaintenanceMarginRateListRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              maintenanceMarginRatePO_ = new java.util.ArrayList<MaintenanceMarginRatePO>();
              mutable_bitField0_ |= 0x00000001;
            }
            maintenanceMarginRatePO_.add(
                input.readMessage(MaintenanceMarginRatePO.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        maintenanceMarginRatePO_ = java.util.Collections.unmodifiableList(maintenanceMarginRatePO_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MaintenanceMarginRateBizServiceProto.internal_static_maintenanceMarginRate_MaintenanceMarginRateListRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MaintenanceMarginRateBizServiceProto.internal_static_maintenanceMarginRate_MaintenanceMarginRateListRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MaintenanceMarginRateListRequest.class, Builder.class);
  }

  public static final int MAINTENANCEMARGINRATEPO_FIELD_NUMBER = 1;
  private java.util.List<MaintenanceMarginRatePO> maintenanceMarginRatePO_;
  /**
   * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
   */
  public java.util.List<MaintenanceMarginRatePO> getMaintenanceMarginRatePOList() {
    return maintenanceMarginRatePO_;
  }
  /**
   * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
   */
  public java.util.List<? extends MaintenanceMarginRatePOOrBuilder>
      getMaintenanceMarginRatePOOrBuilderList() {
    return maintenanceMarginRatePO_;
  }
  /**
   * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
   */
  public int getMaintenanceMarginRatePOCount() {
    return maintenanceMarginRatePO_.size();
  }
  /**
   * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
   */
  public MaintenanceMarginRatePO getMaintenanceMarginRatePO(int index) {
    return maintenanceMarginRatePO_.get(index);
  }
  /**
   * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
   */
  public MaintenanceMarginRatePOOrBuilder getMaintenanceMarginRatePOOrBuilder(
      int index) {
    return maintenanceMarginRatePO_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < maintenanceMarginRatePO_.size(); i++) {
      output.writeMessage(1, maintenanceMarginRatePO_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < maintenanceMarginRatePO_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, maintenanceMarginRatePO_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MaintenanceMarginRateListRequest)) {
      return super.equals(obj);
    }
    MaintenanceMarginRateListRequest other = (MaintenanceMarginRateListRequest) obj;

    if (!getMaintenanceMarginRatePOList()
        .equals(other.getMaintenanceMarginRatePOList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMaintenanceMarginRatePOCount() > 0) {
      hash = (37 * hash) + MAINTENANCEMARGINRATEPO_FIELD_NUMBER;
      hash = (53 * hash) + getMaintenanceMarginRatePOList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MaintenanceMarginRateListRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MaintenanceMarginRateListRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MaintenanceMarginRateListRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MaintenanceMarginRateListRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MaintenanceMarginRateListRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MaintenanceMarginRateListRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MaintenanceMarginRateListRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MaintenanceMarginRateListRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MaintenanceMarginRateListRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MaintenanceMarginRateListRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MaintenanceMarginRateListRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MaintenanceMarginRateListRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MaintenanceMarginRateListRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code maintenanceMarginRate.MaintenanceMarginRateListRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:maintenanceMarginRate.MaintenanceMarginRateListRequest)
      MaintenanceMarginRateListRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MaintenanceMarginRateBizServiceProto.internal_static_maintenanceMarginRate_MaintenanceMarginRateListRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MaintenanceMarginRateBizServiceProto.internal_static_maintenanceMarginRate_MaintenanceMarginRateListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MaintenanceMarginRateListRequest.class, Builder.class);
    }

    // Construct using com.bjs.contract.proto.maintenanceMarginRate.MaintenanceMarginRateListRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMaintenanceMarginRatePOFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (maintenanceMarginRatePOBuilder_ == null) {
        maintenanceMarginRatePO_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        maintenanceMarginRatePOBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MaintenanceMarginRateBizServiceProto.internal_static_maintenanceMarginRate_MaintenanceMarginRateListRequest_descriptor;
    }

    @Override
    public MaintenanceMarginRateListRequest getDefaultInstanceForType() {
      return MaintenanceMarginRateListRequest.getDefaultInstance();
    }

    @Override
    public MaintenanceMarginRateListRequest build() {
      MaintenanceMarginRateListRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public MaintenanceMarginRateListRequest buildPartial() {
      MaintenanceMarginRateListRequest result = new MaintenanceMarginRateListRequest(this);
      int from_bitField0_ = bitField0_;
      if (maintenanceMarginRatePOBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          maintenanceMarginRatePO_ = java.util.Collections.unmodifiableList(maintenanceMarginRatePO_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.maintenanceMarginRatePO_ = maintenanceMarginRatePO_;
      } else {
        result.maintenanceMarginRatePO_ = maintenanceMarginRatePOBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MaintenanceMarginRateListRequest) {
        return mergeFrom((MaintenanceMarginRateListRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MaintenanceMarginRateListRequest other) {
      if (other == MaintenanceMarginRateListRequest.getDefaultInstance()) return this;
      if (maintenanceMarginRatePOBuilder_ == null) {
        if (!other.maintenanceMarginRatePO_.isEmpty()) {
          if (maintenanceMarginRatePO_.isEmpty()) {
            maintenanceMarginRatePO_ = other.maintenanceMarginRatePO_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMaintenanceMarginRatePOIsMutable();
            maintenanceMarginRatePO_.addAll(other.maintenanceMarginRatePO_);
          }
          onChanged();
        }
      } else {
        if (!other.maintenanceMarginRatePO_.isEmpty()) {
          if (maintenanceMarginRatePOBuilder_.isEmpty()) {
            maintenanceMarginRatePOBuilder_.dispose();
            maintenanceMarginRatePOBuilder_ = null;
            maintenanceMarginRatePO_ = other.maintenanceMarginRatePO_;
            bitField0_ = (bitField0_ & ~0x00000001);
            maintenanceMarginRatePOBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMaintenanceMarginRatePOFieldBuilder() : null;
          } else {
            maintenanceMarginRatePOBuilder_.addAllMessages(other.maintenanceMarginRatePO_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MaintenanceMarginRateListRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MaintenanceMarginRateListRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<MaintenanceMarginRatePO> maintenanceMarginRatePO_ =
      java.util.Collections.emptyList();
    private void ensureMaintenanceMarginRatePOIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        maintenanceMarginRatePO_ = new java.util.ArrayList<MaintenanceMarginRatePO>(maintenanceMarginRatePO_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        MaintenanceMarginRatePO, MaintenanceMarginRatePO.Builder, MaintenanceMarginRatePOOrBuilder> maintenanceMarginRatePOBuilder_;

    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public java.util.List<MaintenanceMarginRatePO> getMaintenanceMarginRatePOList() {
      if (maintenanceMarginRatePOBuilder_ == null) {
        return java.util.Collections.unmodifiableList(maintenanceMarginRatePO_);
      } else {
        return maintenanceMarginRatePOBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public int getMaintenanceMarginRatePOCount() {
      if (maintenanceMarginRatePOBuilder_ == null) {
        return maintenanceMarginRatePO_.size();
      } else {
        return maintenanceMarginRatePOBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public MaintenanceMarginRatePO getMaintenanceMarginRatePO(int index) {
      if (maintenanceMarginRatePOBuilder_ == null) {
        return maintenanceMarginRatePO_.get(index);
      } else {
        return maintenanceMarginRatePOBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public Builder setMaintenanceMarginRatePO(
        int index, MaintenanceMarginRatePO value) {
      if (maintenanceMarginRatePOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMaintenanceMarginRatePOIsMutable();
        maintenanceMarginRatePO_.set(index, value);
        onChanged();
      } else {
        maintenanceMarginRatePOBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public Builder setMaintenanceMarginRatePO(
        int index, MaintenanceMarginRatePO.Builder builderForValue) {
      if (maintenanceMarginRatePOBuilder_ == null) {
        ensureMaintenanceMarginRatePOIsMutable();
        maintenanceMarginRatePO_.set(index, builderForValue.build());
        onChanged();
      } else {
        maintenanceMarginRatePOBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public Builder addMaintenanceMarginRatePO(MaintenanceMarginRatePO value) {
      if (maintenanceMarginRatePOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMaintenanceMarginRatePOIsMutable();
        maintenanceMarginRatePO_.add(value);
        onChanged();
      } else {
        maintenanceMarginRatePOBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public Builder addMaintenanceMarginRatePO(
        int index, MaintenanceMarginRatePO value) {
      if (maintenanceMarginRatePOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMaintenanceMarginRatePOIsMutable();
        maintenanceMarginRatePO_.add(index, value);
        onChanged();
      } else {
        maintenanceMarginRatePOBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public Builder addMaintenanceMarginRatePO(
        MaintenanceMarginRatePO.Builder builderForValue) {
      if (maintenanceMarginRatePOBuilder_ == null) {
        ensureMaintenanceMarginRatePOIsMutable();
        maintenanceMarginRatePO_.add(builderForValue.build());
        onChanged();
      } else {
        maintenanceMarginRatePOBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public Builder addMaintenanceMarginRatePO(
        int index, MaintenanceMarginRatePO.Builder builderForValue) {
      if (maintenanceMarginRatePOBuilder_ == null) {
        ensureMaintenanceMarginRatePOIsMutable();
        maintenanceMarginRatePO_.add(index, builderForValue.build());
        onChanged();
      } else {
        maintenanceMarginRatePOBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public Builder addAllMaintenanceMarginRatePO(
        Iterable<? extends MaintenanceMarginRatePO> values) {
      if (maintenanceMarginRatePOBuilder_ == null) {
        ensureMaintenanceMarginRatePOIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, maintenanceMarginRatePO_);
        onChanged();
      } else {
        maintenanceMarginRatePOBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public Builder clearMaintenanceMarginRatePO() {
      if (maintenanceMarginRatePOBuilder_ == null) {
        maintenanceMarginRatePO_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        maintenanceMarginRatePOBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public Builder removeMaintenanceMarginRatePO(int index) {
      if (maintenanceMarginRatePOBuilder_ == null) {
        ensureMaintenanceMarginRatePOIsMutable();
        maintenanceMarginRatePO_.remove(index);
        onChanged();
      } else {
        maintenanceMarginRatePOBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public MaintenanceMarginRatePO.Builder getMaintenanceMarginRatePOBuilder(
        int index) {
      return getMaintenanceMarginRatePOFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public MaintenanceMarginRatePOOrBuilder getMaintenanceMarginRatePOOrBuilder(
        int index) {
      if (maintenanceMarginRatePOBuilder_ == null) {
        return maintenanceMarginRatePO_.get(index);  } else {
        return maintenanceMarginRatePOBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public java.util.List<? extends MaintenanceMarginRatePOOrBuilder>
         getMaintenanceMarginRatePOOrBuilderList() {
      if (maintenanceMarginRatePOBuilder_ != null) {
        return maintenanceMarginRatePOBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(maintenanceMarginRatePO_);
      }
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public MaintenanceMarginRatePO.Builder addMaintenanceMarginRatePOBuilder() {
      return getMaintenanceMarginRatePOFieldBuilder().addBuilder(
          MaintenanceMarginRatePO.getDefaultInstance());
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public MaintenanceMarginRatePO.Builder addMaintenanceMarginRatePOBuilder(
        int index) {
      return getMaintenanceMarginRatePOFieldBuilder().addBuilder(
          index, MaintenanceMarginRatePO.getDefaultInstance());
    }
    /**
     * <code>repeated .maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 1;</code>
     */
    public java.util.List<MaintenanceMarginRatePO.Builder>
         getMaintenanceMarginRatePOBuilderList() {
      return getMaintenanceMarginRatePOFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        MaintenanceMarginRatePO, MaintenanceMarginRatePO.Builder, MaintenanceMarginRatePOOrBuilder>
        getMaintenanceMarginRatePOFieldBuilder() {
      if (maintenanceMarginRatePOBuilder_ == null) {
        maintenanceMarginRatePOBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            MaintenanceMarginRatePO, MaintenanceMarginRatePO.Builder, MaintenanceMarginRatePOOrBuilder>(
                maintenanceMarginRatePO_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        maintenanceMarginRatePO_ = null;
      }
      return maintenanceMarginRatePOBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:maintenanceMarginRate.MaintenanceMarginRateListRequest)
  }

  // @@protoc_insertion_point(class_scope:maintenanceMarginRate.MaintenanceMarginRateListRequest)
  private static final MaintenanceMarginRateListRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MaintenanceMarginRateListRequest();
  }

  public static MaintenanceMarginRateListRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MaintenanceMarginRateListRequest>
      PARSER = new com.google.protobuf.AbstractParser<MaintenanceMarginRateListRequest>() {
    @Override
    public MaintenanceMarginRateListRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MaintenanceMarginRateListRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MaintenanceMarginRateListRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MaintenanceMarginRateListRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public MaintenanceMarginRateListRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

