// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MaintenanceMarginRateService.proto

package com.bjs.contract.proto.maintenanceMarginRate;

public interface MaintenanceMarginRatePageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maintenanceMarginRate.MaintenanceMarginRatePageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1;</code>
   */
  int getPage();

  /**
   * <code>int32 size = 2;</code>
   */
  int getSize();

  /**
   * <code>.maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 3;</code>
   */
  boolean hasMaintenanceMarginRatePO();
  /**
   * <code>.maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 3;</code>
   */
  MaintenanceMarginRatePO getMaintenanceMarginRatePO();
  /**
   * <code>.maintenanceMarginRate.MaintenanceMarginRatePO maintenanceMarginRatePO = 3;</code>
   */
  MaintenanceMarginRatePOOrBuilder getMaintenanceMarginRatePOOrBuilder();
}
