// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserLeverageService.proto

package com.bjs.contract.proto.userLeverage;

public interface UserLeverageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userLeverage.UserLeverageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>.userLeverage.UserLeveragePO userLeveragePO = 2;</code>
   */
  boolean hasUserLeveragePO();
  /**
   * <code>.userLeverage.UserLeveragePO userLeveragePO = 2;</code>
   */
  UserLeveragePO getUserLeveragePO();
  /**
   * <code>.userLeverage.UserLeveragePO userLeveragePO = 2;</code>
   */
  UserLeveragePOOrBuilder getUserLeveragePOOrBuilder();
}
