// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CoTriggerOrderService.proto

package com.bjs.contract.proto.coTriggerOrder;

/**
 * Protobuf type {@code coTriggerOrder.CoTriggerOrderListRequest}
 */
public  final class CoTriggerOrderListRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coTriggerOrder.CoTriggerOrderListRequest)
    CoTriggerOrderListRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CoTriggerOrderListRequest.newBuilder() to construct.
  private CoTriggerOrderListRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CoTriggerOrderListRequest() {
    coTriggerOrderPO_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CoTriggerOrderListRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              coTriggerOrderPO_ = new java.util.ArrayList<CoTriggerOrderPO>();
              mutable_bitField0_ |= 0x00000001;
            }
            coTriggerOrderPO_.add(
                input.readMessage(CoTriggerOrderPO.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        coTriggerOrderPO_ = java.util.Collections.unmodifiableList(coTriggerOrderPO_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CoTriggerOrderBizServiceProto.internal_static_coTriggerOrder_CoTriggerOrderListRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CoTriggerOrderBizServiceProto.internal_static_coTriggerOrder_CoTriggerOrderListRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CoTriggerOrderListRequest.class, Builder.class);
  }

  public static final int COTRIGGERORDERPO_FIELD_NUMBER = 1;
  private java.util.List<CoTriggerOrderPO> coTriggerOrderPO_;
  /**
   * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
   */
  public java.util.List<CoTriggerOrderPO> getCoTriggerOrderPOList() {
    return coTriggerOrderPO_;
  }
  /**
   * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
   */
  public java.util.List<? extends CoTriggerOrderPOOrBuilder>
      getCoTriggerOrderPOOrBuilderList() {
    return coTriggerOrderPO_;
  }
  /**
   * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
   */
  public int getCoTriggerOrderPOCount() {
    return coTriggerOrderPO_.size();
  }
  /**
   * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
   */
  public CoTriggerOrderPO getCoTriggerOrderPO(int index) {
    return coTriggerOrderPO_.get(index);
  }
  /**
   * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
   */
  public CoTriggerOrderPOOrBuilder getCoTriggerOrderPOOrBuilder(
      int index) {
    return coTriggerOrderPO_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < coTriggerOrderPO_.size(); i++) {
      output.writeMessage(1, coTriggerOrderPO_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < coTriggerOrderPO_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, coTriggerOrderPO_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CoTriggerOrderListRequest)) {
      return super.equals(obj);
    }
    CoTriggerOrderListRequest other = (CoTriggerOrderListRequest) obj;

    if (!getCoTriggerOrderPOList()
        .equals(other.getCoTriggerOrderPOList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCoTriggerOrderPOCount() > 0) {
      hash = (37 * hash) + COTRIGGERORDERPO_FIELD_NUMBER;
      hash = (53 * hash) + getCoTriggerOrderPOList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CoTriggerOrderListRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CoTriggerOrderListRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CoTriggerOrderListRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CoTriggerOrderListRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CoTriggerOrderListRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CoTriggerOrderListRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CoTriggerOrderListRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CoTriggerOrderListRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CoTriggerOrderListRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CoTriggerOrderListRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CoTriggerOrderListRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CoTriggerOrderListRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CoTriggerOrderListRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code coTriggerOrder.CoTriggerOrderListRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coTriggerOrder.CoTriggerOrderListRequest)
      CoTriggerOrderListRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CoTriggerOrderBizServiceProto.internal_static_coTriggerOrder_CoTriggerOrderListRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CoTriggerOrderBizServiceProto.internal_static_coTriggerOrder_CoTriggerOrderListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CoTriggerOrderListRequest.class, Builder.class);
    }

    // Construct using com.bjs.contract.proto.coTriggerOrder.CoTriggerOrderListRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCoTriggerOrderPOFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (coTriggerOrderPOBuilder_ == null) {
        coTriggerOrderPO_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        coTriggerOrderPOBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CoTriggerOrderBizServiceProto.internal_static_coTriggerOrder_CoTriggerOrderListRequest_descriptor;
    }

    @Override
    public CoTriggerOrderListRequest getDefaultInstanceForType() {
      return CoTriggerOrderListRequest.getDefaultInstance();
    }

    @Override
    public CoTriggerOrderListRequest build() {
      CoTriggerOrderListRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CoTriggerOrderListRequest buildPartial() {
      CoTriggerOrderListRequest result = new CoTriggerOrderListRequest(this);
      int from_bitField0_ = bitField0_;
      if (coTriggerOrderPOBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          coTriggerOrderPO_ = java.util.Collections.unmodifiableList(coTriggerOrderPO_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.coTriggerOrderPO_ = coTriggerOrderPO_;
      } else {
        result.coTriggerOrderPO_ = coTriggerOrderPOBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CoTriggerOrderListRequest) {
        return mergeFrom((CoTriggerOrderListRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CoTriggerOrderListRequest other) {
      if (other == CoTriggerOrderListRequest.getDefaultInstance()) return this;
      if (coTriggerOrderPOBuilder_ == null) {
        if (!other.coTriggerOrderPO_.isEmpty()) {
          if (coTriggerOrderPO_.isEmpty()) {
            coTriggerOrderPO_ = other.coTriggerOrderPO_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCoTriggerOrderPOIsMutable();
            coTriggerOrderPO_.addAll(other.coTriggerOrderPO_);
          }
          onChanged();
        }
      } else {
        if (!other.coTriggerOrderPO_.isEmpty()) {
          if (coTriggerOrderPOBuilder_.isEmpty()) {
            coTriggerOrderPOBuilder_.dispose();
            coTriggerOrderPOBuilder_ = null;
            coTriggerOrderPO_ = other.coTriggerOrderPO_;
            bitField0_ = (bitField0_ & ~0x00000001);
            coTriggerOrderPOBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCoTriggerOrderPOFieldBuilder() : null;
          } else {
            coTriggerOrderPOBuilder_.addAllMessages(other.coTriggerOrderPO_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CoTriggerOrderListRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CoTriggerOrderListRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<CoTriggerOrderPO> coTriggerOrderPO_ =
      java.util.Collections.emptyList();
    private void ensureCoTriggerOrderPOIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        coTriggerOrderPO_ = new java.util.ArrayList<CoTriggerOrderPO>(coTriggerOrderPO_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        CoTriggerOrderPO, CoTriggerOrderPO.Builder, CoTriggerOrderPOOrBuilder> coTriggerOrderPOBuilder_;

    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public java.util.List<CoTriggerOrderPO> getCoTriggerOrderPOList() {
      if (coTriggerOrderPOBuilder_ == null) {
        return java.util.Collections.unmodifiableList(coTriggerOrderPO_);
      } else {
        return coTriggerOrderPOBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public int getCoTriggerOrderPOCount() {
      if (coTriggerOrderPOBuilder_ == null) {
        return coTriggerOrderPO_.size();
      } else {
        return coTriggerOrderPOBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public CoTriggerOrderPO getCoTriggerOrderPO(int index) {
      if (coTriggerOrderPOBuilder_ == null) {
        return coTriggerOrderPO_.get(index);
      } else {
        return coTriggerOrderPOBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public Builder setCoTriggerOrderPO(
        int index, CoTriggerOrderPO value) {
      if (coTriggerOrderPOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoTriggerOrderPOIsMutable();
        coTriggerOrderPO_.set(index, value);
        onChanged();
      } else {
        coTriggerOrderPOBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public Builder setCoTriggerOrderPO(
        int index, CoTriggerOrderPO.Builder builderForValue) {
      if (coTriggerOrderPOBuilder_ == null) {
        ensureCoTriggerOrderPOIsMutable();
        coTriggerOrderPO_.set(index, builderForValue.build());
        onChanged();
      } else {
        coTriggerOrderPOBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public Builder addCoTriggerOrderPO(CoTriggerOrderPO value) {
      if (coTriggerOrderPOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoTriggerOrderPOIsMutable();
        coTriggerOrderPO_.add(value);
        onChanged();
      } else {
        coTriggerOrderPOBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public Builder addCoTriggerOrderPO(
        int index, CoTriggerOrderPO value) {
      if (coTriggerOrderPOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoTriggerOrderPOIsMutable();
        coTriggerOrderPO_.add(index, value);
        onChanged();
      } else {
        coTriggerOrderPOBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public Builder addCoTriggerOrderPO(
        CoTriggerOrderPO.Builder builderForValue) {
      if (coTriggerOrderPOBuilder_ == null) {
        ensureCoTriggerOrderPOIsMutable();
        coTriggerOrderPO_.add(builderForValue.build());
        onChanged();
      } else {
        coTriggerOrderPOBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public Builder addCoTriggerOrderPO(
        int index, CoTriggerOrderPO.Builder builderForValue) {
      if (coTriggerOrderPOBuilder_ == null) {
        ensureCoTriggerOrderPOIsMutable();
        coTriggerOrderPO_.add(index, builderForValue.build());
        onChanged();
      } else {
        coTriggerOrderPOBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public Builder addAllCoTriggerOrderPO(
        Iterable<? extends CoTriggerOrderPO> values) {
      if (coTriggerOrderPOBuilder_ == null) {
        ensureCoTriggerOrderPOIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, coTriggerOrderPO_);
        onChanged();
      } else {
        coTriggerOrderPOBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public Builder clearCoTriggerOrderPO() {
      if (coTriggerOrderPOBuilder_ == null) {
        coTriggerOrderPO_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        coTriggerOrderPOBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public Builder removeCoTriggerOrderPO(int index) {
      if (coTriggerOrderPOBuilder_ == null) {
        ensureCoTriggerOrderPOIsMutable();
        coTriggerOrderPO_.remove(index);
        onChanged();
      } else {
        coTriggerOrderPOBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public CoTriggerOrderPO.Builder getCoTriggerOrderPOBuilder(
        int index) {
      return getCoTriggerOrderPOFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public CoTriggerOrderPOOrBuilder getCoTriggerOrderPOOrBuilder(
        int index) {
      if (coTriggerOrderPOBuilder_ == null) {
        return coTriggerOrderPO_.get(index);  } else {
        return coTriggerOrderPOBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public java.util.List<? extends CoTriggerOrderPOOrBuilder>
         getCoTriggerOrderPOOrBuilderList() {
      if (coTriggerOrderPOBuilder_ != null) {
        return coTriggerOrderPOBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(coTriggerOrderPO_);
      }
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public CoTriggerOrderPO.Builder addCoTriggerOrderPOBuilder() {
      return getCoTriggerOrderPOFieldBuilder().addBuilder(
          CoTriggerOrderPO.getDefaultInstance());
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public CoTriggerOrderPO.Builder addCoTriggerOrderPOBuilder(
        int index) {
      return getCoTriggerOrderPOFieldBuilder().addBuilder(
          index, CoTriggerOrderPO.getDefaultInstance());
    }
    /**
     * <code>repeated .coTriggerOrder.CoTriggerOrderPO coTriggerOrderPO = 1;</code>
     */
    public java.util.List<CoTriggerOrderPO.Builder>
         getCoTriggerOrderPOBuilderList() {
      return getCoTriggerOrderPOFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        CoTriggerOrderPO, CoTriggerOrderPO.Builder, CoTriggerOrderPOOrBuilder>
        getCoTriggerOrderPOFieldBuilder() {
      if (coTriggerOrderPOBuilder_ == null) {
        coTriggerOrderPOBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            CoTriggerOrderPO, CoTriggerOrderPO.Builder, CoTriggerOrderPOOrBuilder>(
                coTriggerOrderPO_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        coTriggerOrderPO_ = null;
      }
      return coTriggerOrderPOBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:coTriggerOrder.CoTriggerOrderListRequest)
  }

  // @@protoc_insertion_point(class_scope:coTriggerOrder.CoTriggerOrderListRequest)
  private static final CoTriggerOrderListRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CoTriggerOrderListRequest();
  }

  public static CoTriggerOrderListRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CoTriggerOrderListRequest>
      PARSER = new com.google.protobuf.AbstractParser<CoTriggerOrderListRequest>() {
    @Override
    public CoTriggerOrderListRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CoTriggerOrderListRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CoTriggerOrderListRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CoTriggerOrderListRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public CoTriggerOrderListRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

