// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.bjs.contract.proto.user;

public interface UserReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.UserReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();

  /**
   * <code>string message = 2;</code>
   */
  String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.user.UserPO userPO = 3;</code>
   */
  boolean hasUserPO();
  /**
   * <code>.user.UserPO userPO = 3;</code>
   */
  UserPO getUserPO();
  /**
   * <code>.user.UserPO userPO = 3;</code>
   */
  UserPOOrBuilder getUserPOOrBuilder();
}
