// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.bjs.contract.proto.user;

public interface UserPageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.UserPageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1;</code>
   */
  int getPage();

  /**
   * <code>int32 size = 2;</code>
   */
  int getSize();

  /**
   * <code>.user.UserPO userPO = 3;</code>
   */
  boolean hasUserPO();
  /**
   * <code>.user.UserPO userPO = 3;</code>
   */
  UserPO getUserPO();
  /**
   * <code>.user.UserPO userPO = 3;</code>
   */
  UserPOOrBuilder getUserPOOrBuilder();
}
