// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.bjs.contract.proto.user;

public interface UserListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.UserListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .user.UserPO userPO = 1;</code>
   */
  java.util.List<UserPO>
      getUserPOList();
  /**
   * <code>repeated .user.UserPO userPO = 1;</code>
   */
  UserPO getUserPO(int index);
  /**
   * <code>repeated .user.UserPO userPO = 1;</code>
   */
  int getUserPOCount();
  /**
   * <code>repeated .user.UserPO userPO = 1;</code>
   */
  java.util.List<? extends UserPOOrBuilder>
      getUserPOOrBuilderList();
  /**
   * <code>repeated .user.UserPO userPO = 1;</code>
   */
  UserPOOrBuilder getUserPOOrBuilder(
      int index);
}
