// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContractConfigService.proto

package com.bjs.contract.proto.contractConfig;

public interface ContractConfigReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:contractConfig.ContractConfigReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();

  /**
   * <code>string message = 2;</code>
   */
  String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.contractConfig.ContractConfigPO contractConfigPO = 3;</code>
   */
  boolean hasContractConfigPO();
  /**
   * <code>.contractConfig.ContractConfigPO contractConfigPO = 3;</code>
   */
  ContractConfigPO getContractConfigPO();
  /**
   * <code>.contractConfig.ContractConfigPO contractConfigPO = 3;</code>
   */
  ContractConfigPOOrBuilder getContractConfigPOOrBuilder();
}
