// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContractConfigPO.proto

package com.bjs.contract.proto.contractConfig;

public final class ContractConfigPOProto {
  private ContractConfigPOProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_contractConfig_ContractConfigPO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_contractConfig_ContractConfigPO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026ContractConfigPO.proto\022\016contractConfig" +
      "\032\037google/protobuf/timestamp.proto\032\036googl" +
      "e/protobuf/wrappers.proto\"\277\007\n\020ContractCo" +
      "nfigPO\022\'\n\002id\030\001 \001(\0132\033.google.protobuf.Int" +
      "64Value\022\016\n\006symbol\030\002 \001(\t\022\014\n\004base\030\003 \001(\t\022\r\n" +
      "\005quote\030\004 \001(\t\022\024\n\014contractName\030\005 \001(\t\022\031\n\021co" +
      "ntractOtherName\030\006 \001(\t\022\032\n\022capitalInterval" +
      "Min\030\007 \001(\t\022\032\n\022capitalIntervalMax\030\010 \001(\t\022\030\n" +
      "\020openMakerFeeRate\030\t \001(\t\022\030\n\020openTakerFeeR" +
      "ate\030\n \001(\t\022\031\n\021closeMakerFeeRate\030\013 \001(\t\022\031\n\021" +
      "closeTakerFeeRate\030\014 \001(\t\022\023\n\013minMakerFee\030\r" +
      " \001(\t\022\023\n\013minTakerFee\030\016 \001(\t\0222\n\rriskAlarmWe" +
      "ak\030\017 \001(\0132\033.google.protobuf.Int32Value\0224\n" +
      "\017riskAlarmMiddle\030\020 \001(\0132\033.google.protobuf" +
      ".Int32Value\0224\n\017riskAlarmStrong\030\021 \001(\0132\033.g" +
      "oogle.protobuf.Int32Value\022\026\n\016priceLimitR" +
      "ate\030\022 \001(\t\022+\n\006status\030\023 \001(\0132\033.google.proto" +
      "buf.Int32Value\022)\n\004show\030\024 \001(\0132\033.google.pr" +
      "otobuf.Int32Value\022)\n\005ctime\030\025 \001(\0132\032.googl" +
      "e.protobuf.Timestamp\022)\n\005mtime\030\026 \001(\0132\032.go" +
      "ogle.protobuf.Timestamp\022\023\n\013minOpenBase\030\027" +
      " \001(\t\022\023\n\013maxOpenBase\030\030 \001(\t\022\024\n\014minOpenQuot" +
      "e\030\031 \001(\t\022\024\n\014maxOpenQuote\030\032 \001(\t\0222\n\rbasePre" +
      "cision\030\033 \001(\0132\033.google.protobuf.Int32Valu" +
      "e\0223\n\016quotePrecision\030\034 \001(\0132\033.google.proto" +
      "buf.Int32Value\0223\n\016pricePrecision\030\035 \001(\0132\033" +
      ".google.protobuf.Int32ValueB@\n%com.bjs.c" +
      "ontract.proto.contractConfigB\025ContractCo" +
      "nfigPOProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_contractConfig_ContractConfigPO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_contractConfig_ContractConfigPO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_contractConfig_ContractConfigPO_descriptor,
        new String[] { "Id", "Symbol", "Base", "Quote", "ContractName", "ContractOtherName", "CapitalIntervalMin", "CapitalIntervalMax", "OpenMakerFeeRate", "OpenTakerFeeRate", "CloseMakerFeeRate", "CloseTakerFeeRate", "MinMakerFee", "MinTakerFee", "RiskAlarmWeak", "RiskAlarmMiddle", "RiskAlarmStrong", "PriceLimitRate", "Status", "Show", "Ctime", "Mtime", "MinOpenBase", "MaxOpenBase", "MinOpenQuote", "MaxOpenQuote", "BasePrecision", "QuotePrecision", "PricePrecision", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
