// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto

package com.bjs.contract.proto.account;

public interface AccountRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.AccountRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>.account.AccountPO accountPO = 2;</code>
   */
  boolean hasAccountPO();
  /**
   * <code>.account.AccountPO accountPO = 2;</code>
   */
  AccountPO getAccountPO();
  /**
   * <code>.account.AccountPO accountPO = 2;</code>
   */
  AccountPOOrBuilder getAccountPOOrBuilder();
}
