// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountPO.proto

package com.bjs.contract.proto.account;

public interface AccountPOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.AccountPO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   */
  com.google.protobuf.Int64Value getId();
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getIdOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value uid = 2;</code>
   */
  boolean hasUid();
  /**
   * <code>.google.protobuf.Int64Value uid = 2;</code>
   */
  com.google.protobuf.Int64Value getUid();
  /**
   * <code>.google.protobuf.Int64Value uid = 2;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getUidOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value type = 3;</code>
   */
  boolean hasType();
  /**
   * <code>.google.protobuf.Int32Value type = 3;</code>
   */
  com.google.protobuf.Int32Value getType();
  /**
   * <code>.google.protobuf.Int32Value type = 3;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getTypeOrBuilder();

  /**
   * <code>string balance = 4;</code>
   */
  String getBalance();
  /**
   * <code>string balance = 4;</code>
   */
  com.google.protobuf.ByteString
      getBalanceBytes();

  /**
   * <code>string tag = 5;</code>
   */
  String getTag();
  /**
   * <code>string tag = 5;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>.google.protobuf.Timestamp ctime = 6;</code>
   */
  boolean hasCtime();
  /**
   * <code>.google.protobuf.Timestamp ctime = 6;</code>
   */
  com.google.protobuf.Timestamp getCtime();
  /**
   * <code>.google.protobuf.Timestamp ctime = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCtimeOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp mtime = 7;</code>
   */
  boolean hasMtime();
  /**
   * <code>.google.protobuf.Timestamp mtime = 7;</code>
   */
  com.google.protobuf.Timestamp getMtime();
  /**
   * <code>.google.protobuf.Timestamp mtime = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getMtimeOrBuilder();
}
