// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto

package com.bjs.contract.proto.account;

/**
 * Protobuf type {@code account.AccountRequest}
 */
public  final class AccountRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:account.AccountRequest)
    AccountRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AccountRequest.newBuilder() to construct.
  private AccountRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AccountRequest() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AccountRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            AccountPO.Builder subBuilder = null;
            if (accountPO_ != null) {
              subBuilder = accountPO_.toBuilder();
            }
            accountPO_ = input.readMessage(AccountPO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(accountPO_);
              accountPO_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return AccountBizServiceProto.internal_static_account_AccountRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return AccountBizServiceProto.internal_static_account_AccountRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AccountRequest.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int ACCOUNTPO_FIELD_NUMBER = 2;
  private AccountPO accountPO_;
  /**
   * <code>.account.AccountPO accountPO = 2;</code>
   */
  public boolean hasAccountPO() {
    return accountPO_ != null;
  }
  /**
   * <code>.account.AccountPO accountPO = 2;</code>
   */
  public AccountPO getAccountPO() {
    return accountPO_ == null ? AccountPO.getDefaultInstance() : accountPO_;
  }
  /**
   * <code>.account.AccountPO accountPO = 2;</code>
   */
  public AccountPOOrBuilder getAccountPOOrBuilder() {
    return getAccountPO();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (accountPO_ != null) {
      output.writeMessage(2, getAccountPO());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (accountPO_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAccountPO());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AccountRequest)) {
      return super.equals(obj);
    }
    AccountRequest other = (AccountRequest) obj;

    if (getId()
        != other.getId()) return false;
    if (hasAccountPO() != other.hasAccountPO()) return false;
    if (hasAccountPO()) {
      if (!getAccountPO()
          .equals(other.getAccountPO())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (hasAccountPO()) {
      hash = (37 * hash) + ACCOUNTPO_FIELD_NUMBER;
      hash = (53 * hash) + getAccountPO().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AccountRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AccountRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AccountRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AccountRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AccountRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AccountRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AccountRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AccountRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AccountRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AccountRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AccountRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AccountRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AccountRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code account.AccountRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:account.AccountRequest)
      AccountRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AccountBizServiceProto.internal_static_account_AccountRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AccountBizServiceProto.internal_static_account_AccountRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AccountRequest.class, Builder.class);
    }

    // Construct using com.bjs.contract.proto.account.AccountRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      if (accountPOBuilder_ == null) {
        accountPO_ = null;
      } else {
        accountPO_ = null;
        accountPOBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return AccountBizServiceProto.internal_static_account_AccountRequest_descriptor;
    }

    @Override
    public AccountRequest getDefaultInstanceForType() {
      return AccountRequest.getDefaultInstance();
    }

    @Override
    public AccountRequest build() {
      AccountRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public AccountRequest buildPartial() {
      AccountRequest result = new AccountRequest(this);
      result.id_ = id_;
      if (accountPOBuilder_ == null) {
        result.accountPO_ = accountPO_;
      } else {
        result.accountPO_ = accountPOBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AccountRequest) {
        return mergeFrom((AccountRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AccountRequest other) {
      if (other == AccountRequest.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.hasAccountPO()) {
        mergeAccountPO(other.getAccountPO());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AccountRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AccountRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private AccountPO accountPO_;
    private com.google.protobuf.SingleFieldBuilderV3<
        AccountPO, AccountPO.Builder, AccountPOOrBuilder> accountPOBuilder_;
    /**
     * <code>.account.AccountPO accountPO = 2;</code>
     */
    public boolean hasAccountPO() {
      return accountPOBuilder_ != null || accountPO_ != null;
    }
    /**
     * <code>.account.AccountPO accountPO = 2;</code>
     */
    public AccountPO getAccountPO() {
      if (accountPOBuilder_ == null) {
        return accountPO_ == null ? AccountPO.getDefaultInstance() : accountPO_;
      } else {
        return accountPOBuilder_.getMessage();
      }
    }
    /**
     * <code>.account.AccountPO accountPO = 2;</code>
     */
    public Builder setAccountPO(AccountPO value) {
      if (accountPOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        accountPO_ = value;
        onChanged();
      } else {
        accountPOBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.account.AccountPO accountPO = 2;</code>
     */
    public Builder setAccountPO(
        AccountPO.Builder builderForValue) {
      if (accountPOBuilder_ == null) {
        accountPO_ = builderForValue.build();
        onChanged();
      } else {
        accountPOBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.account.AccountPO accountPO = 2;</code>
     */
    public Builder mergeAccountPO(AccountPO value) {
      if (accountPOBuilder_ == null) {
        if (accountPO_ != null) {
          accountPO_ =
            AccountPO.newBuilder(accountPO_).mergeFrom(value).buildPartial();
        } else {
          accountPO_ = value;
        }
        onChanged();
      } else {
        accountPOBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.account.AccountPO accountPO = 2;</code>
     */
    public Builder clearAccountPO() {
      if (accountPOBuilder_ == null) {
        accountPO_ = null;
        onChanged();
      } else {
        accountPO_ = null;
        accountPOBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.account.AccountPO accountPO = 2;</code>
     */
    public AccountPO.Builder getAccountPOBuilder() {
      
      onChanged();
      return getAccountPOFieldBuilder().getBuilder();
    }
    /**
     * <code>.account.AccountPO accountPO = 2;</code>
     */
    public AccountPOOrBuilder getAccountPOOrBuilder() {
      if (accountPOBuilder_ != null) {
        return accountPOBuilder_.getMessageOrBuilder();
      } else {
        return accountPO_ == null ?
            AccountPO.getDefaultInstance() : accountPO_;
      }
    }
    /**
     * <code>.account.AccountPO accountPO = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        AccountPO, AccountPO.Builder, AccountPOOrBuilder>
        getAccountPOFieldBuilder() {
      if (accountPOBuilder_ == null) {
        accountPOBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            AccountPO, AccountPO.Builder, AccountPOOrBuilder>(
                getAccountPO(),
                getParentForChildren(),
                isClean());
        accountPO_ = null;
      }
      return accountPOBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:account.AccountRequest)
  }

  // @@protoc_insertion_point(class_scope:account.AccountRequest)
  private static final AccountRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AccountRequest();
  }

  public static AccountRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AccountRequest>
      PARSER = new com.google.protobuf.AbstractParser<AccountRequest>() {
    @Override
    public AccountRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AccountRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AccountRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AccountRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public AccountRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

