// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto

package com.bjs.contract.proto.account;

/**
 * Protobuf type {@code account.UserAccountList}
 */
public  final class UserAccountList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:account.UserAccountList)
    UserAccountListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserAccountList.newBuilder() to construct.
  private UserAccountList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserAccountList() {
    canUseAmount_ = "";
    totalAmount_ = "";
    isolateMargin_ = "";
    lockAmount_ = "";
    totalMargin_ = "";
    symbol_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserAccountList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            canUseAmount_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            totalAmount_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            isolateMargin_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            lockAmount_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            totalMargin_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            symbol_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return AccountBizServiceProto.internal_static_account_UserAccountList_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return AccountBizServiceProto.internal_static_account_UserAccountList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UserAccountList.class, Builder.class);
  }

  public static final int CANUSEAMOUNT_FIELD_NUMBER = 1;
  private volatile Object canUseAmount_;
  /**
   * <code>string canUseAmount = 1;</code>
   */
  public String getCanUseAmount() {
    Object ref = canUseAmount_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      canUseAmount_ = s;
      return s;
    }
  }
  /**
   * <code>string canUseAmount = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCanUseAmountBytes() {
    Object ref = canUseAmount_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      canUseAmount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTALAMOUNT_FIELD_NUMBER = 2;
  private volatile Object totalAmount_;
  /**
   * <code>string totalAmount = 2;</code>
   */
  public String getTotalAmount() {
    Object ref = totalAmount_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      totalAmount_ = s;
      return s;
    }
  }
  /**
   * <code>string totalAmount = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTotalAmountBytes() {
    Object ref = totalAmount_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      totalAmount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISOLATEMARGIN_FIELD_NUMBER = 3;
  private volatile Object isolateMargin_;
  /**
   * <code>string isolateMargin = 3;</code>
   */
  public String getIsolateMargin() {
    Object ref = isolateMargin_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      isolateMargin_ = s;
      return s;
    }
  }
  /**
   * <code>string isolateMargin = 3;</code>
   */
  public com.google.protobuf.ByteString
      getIsolateMarginBytes() {
    Object ref = isolateMargin_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      isolateMargin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCKAMOUNT_FIELD_NUMBER = 4;
  private volatile Object lockAmount_;
  /**
   * <code>string lockAmount = 4;</code>
   */
  public String getLockAmount() {
    Object ref = lockAmount_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      lockAmount_ = s;
      return s;
    }
  }
  /**
   * <code>string lockAmount = 4;</code>
   */
  public com.google.protobuf.ByteString
      getLockAmountBytes() {
    Object ref = lockAmount_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      lockAmount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTALMARGIN_FIELD_NUMBER = 5;
  private volatile Object totalMargin_;
  /**
   * <code>string totalMargin = 5;</code>
   */
  public String getTotalMargin() {
    Object ref = totalMargin_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      totalMargin_ = s;
      return s;
    }
  }
  /**
   * <code>string totalMargin = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTotalMarginBytes() {
    Object ref = totalMargin_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      totalMargin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYMBOL_FIELD_NUMBER = 6;
  private volatile Object symbol_;
  /**
   * <code>string symbol = 6;</code>
   */
  public String getSymbol() {
    Object ref = symbol_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string symbol = 6;</code>
   */
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    Object ref = symbol_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCanUseAmountBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, canUseAmount_);
    }
    if (!getTotalAmountBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, totalAmount_);
    }
    if (!getIsolateMarginBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, isolateMargin_);
    }
    if (!getLockAmountBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, lockAmount_);
    }
    if (!getTotalMarginBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, totalMargin_);
    }
    if (!getSymbolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, symbol_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCanUseAmountBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, canUseAmount_);
    }
    if (!getTotalAmountBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, totalAmount_);
    }
    if (!getIsolateMarginBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, isolateMargin_);
    }
    if (!getLockAmountBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, lockAmount_);
    }
    if (!getTotalMarginBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, totalMargin_);
    }
    if (!getSymbolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, symbol_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof UserAccountList)) {
      return super.equals(obj);
    }
    UserAccountList other = (UserAccountList) obj;

    if (!getCanUseAmount()
        .equals(other.getCanUseAmount())) return false;
    if (!getTotalAmount()
        .equals(other.getTotalAmount())) return false;
    if (!getIsolateMargin()
        .equals(other.getIsolateMargin())) return false;
    if (!getLockAmount()
        .equals(other.getLockAmount())) return false;
    if (!getTotalMargin()
        .equals(other.getTotalMargin())) return false;
    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CANUSEAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getCanUseAmount().hashCode();
    hash = (37 * hash) + TOTALAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getTotalAmount().hashCode();
    hash = (37 * hash) + ISOLATEMARGIN_FIELD_NUMBER;
    hash = (53 * hash) + getIsolateMargin().hashCode();
    hash = (37 * hash) + LOCKAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getLockAmount().hashCode();
    hash = (37 * hash) + TOTALMARGIN_FIELD_NUMBER;
    hash = (53 * hash) + getTotalMargin().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static UserAccountList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UserAccountList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UserAccountList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UserAccountList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UserAccountList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UserAccountList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UserAccountList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UserAccountList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static UserAccountList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static UserAccountList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static UserAccountList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UserAccountList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UserAccountList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code account.UserAccountList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:account.UserAccountList)
      UserAccountListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AccountBizServiceProto.internal_static_account_UserAccountList_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AccountBizServiceProto.internal_static_account_UserAccountList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserAccountList.class, Builder.class);
    }

    // Construct using com.bjs.contract.proto.account.UserAccountList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      canUseAmount_ = "";

      totalAmount_ = "";

      isolateMargin_ = "";

      lockAmount_ = "";

      totalMargin_ = "";

      symbol_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return AccountBizServiceProto.internal_static_account_UserAccountList_descriptor;
    }

    @Override
    public UserAccountList getDefaultInstanceForType() {
      return UserAccountList.getDefaultInstance();
    }

    @Override
    public UserAccountList build() {
      UserAccountList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public UserAccountList buildPartial() {
      UserAccountList result = new UserAccountList(this);
      result.canUseAmount_ = canUseAmount_;
      result.totalAmount_ = totalAmount_;
      result.isolateMargin_ = isolateMargin_;
      result.lockAmount_ = lockAmount_;
      result.totalMargin_ = totalMargin_;
      result.symbol_ = symbol_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UserAccountList) {
        return mergeFrom((UserAccountList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UserAccountList other) {
      if (other == UserAccountList.getDefaultInstance()) return this;
      if (!other.getCanUseAmount().isEmpty()) {
        canUseAmount_ = other.canUseAmount_;
        onChanged();
      }
      if (!other.getTotalAmount().isEmpty()) {
        totalAmount_ = other.totalAmount_;
        onChanged();
      }
      if (!other.getIsolateMargin().isEmpty()) {
        isolateMargin_ = other.isolateMargin_;
        onChanged();
      }
      if (!other.getLockAmount().isEmpty()) {
        lockAmount_ = other.lockAmount_;
        onChanged();
      }
      if (!other.getTotalMargin().isEmpty()) {
        totalMargin_ = other.totalMargin_;
        onChanged();
      }
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      UserAccountList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (UserAccountList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object canUseAmount_ = "";
    /**
     * <code>string canUseAmount = 1;</code>
     */
    public String getCanUseAmount() {
      Object ref = canUseAmount_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        canUseAmount_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string canUseAmount = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCanUseAmountBytes() {
      Object ref = canUseAmount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        canUseAmount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string canUseAmount = 1;</code>
     */
    public Builder setCanUseAmount(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      canUseAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string canUseAmount = 1;</code>
     */
    public Builder clearCanUseAmount() {
      
      canUseAmount_ = getDefaultInstance().getCanUseAmount();
      onChanged();
      return this;
    }
    /**
     * <code>string canUseAmount = 1;</code>
     */
    public Builder setCanUseAmountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      canUseAmount_ = value;
      onChanged();
      return this;
    }

    private Object totalAmount_ = "";
    /**
     * <code>string totalAmount = 2;</code>
     */
    public String getTotalAmount() {
      Object ref = totalAmount_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        totalAmount_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string totalAmount = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTotalAmountBytes() {
      Object ref = totalAmount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        totalAmount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string totalAmount = 2;</code>
     */
    public Builder setTotalAmount(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      totalAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string totalAmount = 2;</code>
     */
    public Builder clearTotalAmount() {
      
      totalAmount_ = getDefaultInstance().getTotalAmount();
      onChanged();
      return this;
    }
    /**
     * <code>string totalAmount = 2;</code>
     */
    public Builder setTotalAmountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      totalAmount_ = value;
      onChanged();
      return this;
    }

    private Object isolateMargin_ = "";
    /**
     * <code>string isolateMargin = 3;</code>
     */
    public String getIsolateMargin() {
      Object ref = isolateMargin_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        isolateMargin_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string isolateMargin = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIsolateMarginBytes() {
      Object ref = isolateMargin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        isolateMargin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isolateMargin = 3;</code>
     */
    public Builder setIsolateMargin(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      isolateMargin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string isolateMargin = 3;</code>
     */
    public Builder clearIsolateMargin() {
      
      isolateMargin_ = getDefaultInstance().getIsolateMargin();
      onChanged();
      return this;
    }
    /**
     * <code>string isolateMargin = 3;</code>
     */
    public Builder setIsolateMarginBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      isolateMargin_ = value;
      onChanged();
      return this;
    }

    private Object lockAmount_ = "";
    /**
     * <code>string lockAmount = 4;</code>
     */
    public String getLockAmount() {
      Object ref = lockAmount_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        lockAmount_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string lockAmount = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLockAmountBytes() {
      Object ref = lockAmount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        lockAmount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lockAmount = 4;</code>
     */
    public Builder setLockAmount(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lockAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lockAmount = 4;</code>
     */
    public Builder clearLockAmount() {
      
      lockAmount_ = getDefaultInstance().getLockAmount();
      onChanged();
      return this;
    }
    /**
     * <code>string lockAmount = 4;</code>
     */
    public Builder setLockAmountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lockAmount_ = value;
      onChanged();
      return this;
    }

    private Object totalMargin_ = "";
    /**
     * <code>string totalMargin = 5;</code>
     */
    public String getTotalMargin() {
      Object ref = totalMargin_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        totalMargin_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string totalMargin = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTotalMarginBytes() {
      Object ref = totalMargin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        totalMargin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string totalMargin = 5;</code>
     */
    public Builder setTotalMargin(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      totalMargin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string totalMargin = 5;</code>
     */
    public Builder clearTotalMargin() {
      
      totalMargin_ = getDefaultInstance().getTotalMargin();
      onChanged();
      return this;
    }
    /**
     * <code>string totalMargin = 5;</code>
     */
    public Builder setTotalMarginBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      totalMargin_ = value;
      onChanged();
      return this;
    }

    private Object symbol_ = "";
    /**
     * <code>string symbol = 6;</code>
     */
    public String getSymbol() {
      Object ref = symbol_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string symbol = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symbol = 6;</code>
     */
    public Builder setSymbol(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      symbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 6;</code>
     */
    public Builder clearSymbol() {
      
      symbol_ = getDefaultInstance().getSymbol();
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 6;</code>
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      symbol_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:account.UserAccountList)
  }

  // @@protoc_insertion_point(class_scope:account.UserAccountList)
  private static final UserAccountList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UserAccountList();
  }

  public static UserAccountList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserAccountList>
      PARSER = new com.google.protobuf.AbstractParser<UserAccountList>() {
    @Override
    public UserAccountList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserAccountList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserAccountList> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UserAccountList> getParserForType() {
    return PARSER;
  }

  @Override
  public UserAccountList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

