// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SettlementService.proto

package com.bjs.contract.proto.settlement;

public interface SettlementListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:settlement.SettlementListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .settlement.SettlementPO settlementPO = 1;</code>
   */
  java.util.List<SettlementPO>
      getSettlementPOList();
  /**
   * <code>repeated .settlement.SettlementPO settlementPO = 1;</code>
   */
  SettlementPO getSettlementPO(int index);
  /**
   * <code>repeated .settlement.SettlementPO settlementPO = 1;</code>
   */
  int getSettlementPOCount();
  /**
   * <code>repeated .settlement.SettlementPO settlementPO = 1;</code>
   */
  java.util.List<? extends SettlementPOOrBuilder>
      getSettlementPOOrBuilderList();
  /**
   * <code>repeated .settlement.SettlementPO settlementPO = 1;</code>
   */
  SettlementPOOrBuilder getSettlementPOOrBuilder(
      int index);
}
