// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SettlementService.proto

package com.bjs.contract.proto.settlement;

public interface SettlementRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:settlement.SettlementRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>.settlement.SettlementPO settlementPO = 2;</code>
   */
  boolean hasSettlementPO();
  /**
   * <code>.settlement.SettlementPO settlementPO = 2;</code>
   */
  SettlementPO getSettlementPO();
  /**
   * <code>.settlement.SettlementPO settlementPO = 2;</code>
   */
  SettlementPOOrBuilder getSettlementPOOrBuilder();
}
