// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CoTradePO.proto

package com.bjs.contract.proto.coTrade;

public interface CoTradePOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coTrade.CoTradePO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   */
  com.google.protobuf.Int64Value getId();
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getIdOrBuilder();

  /**
   * <code>string symbol = 2;</code>
   */
  String getSymbol();
  /**
   * <code>string symbol = 2;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string tradeNo = 3;</code>
   */
  String getTradeNo();
  /**
   * <code>string tradeNo = 3;</code>
   */
  com.google.protobuf.ByteString
      getTradeNoBytes();

  /**
   * <code>.google.protobuf.Int64Value uid = 4;</code>
   */
  boolean hasUid();
  /**
   * <code>.google.protobuf.Int64Value uid = 4;</code>
   */
  com.google.protobuf.Int64Value getUid();
  /**
   * <code>.google.protobuf.Int64Value uid = 4;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getUidOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value positionId = 5;</code>
   */
  boolean hasPositionId();
  /**
   * <code>.google.protobuf.Int64Value positionId = 5;</code>
   */
  com.google.protobuf.Int64Value getPositionId();
  /**
   * <code>.google.protobuf.Int64Value positionId = 5;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getPositionIdOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value orderId = 6;</code>
   */
  boolean hasOrderId();
  /**
   * <code>.google.protobuf.Int64Value orderId = 6;</code>
   */
  com.google.protobuf.Int64Value getOrderId();
  /**
   * <code>.google.protobuf.Int64Value orderId = 6;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getOrderIdOrBuilder();

  /**
   * <code>string operateType = 7;</code>
   */
  String getOperateType();
  /**
   * <code>string operateType = 7;</code>
   */
  com.google.protobuf.ByteString
      getOperateTypeBytes();

  /**
   * <code>string operateSide = 8;</code>
   */
  String getOperateSide();
  /**
   * <code>string operateSide = 8;</code>
   */
  com.google.protobuf.ByteString
      getOperateSideBytes();

  /**
   * <code>string price = 9;</code>
   */
  String getPrice();
  /**
   * <code>string price = 9;</code>
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>string volumeBase = 10;</code>
   */
  String getVolumeBase();
  /**
   * <code>string volumeBase = 10;</code>
   */
  com.google.protobuf.ByteString
      getVolumeBaseBytes();

  /**
   * <code>string volumeQuote = 11;</code>
   */
  String getVolumeQuote();
  /**
   * <code>string volumeQuote = 11;</code>
   */
  com.google.protobuf.ByteString
      getVolumeQuoteBytes();

  /**
   * <code>string trendSide = 12;</code>
   */
  String getTrendSide();
  /**
   * <code>string trendSide = 12;</code>
   */
  com.google.protobuf.ByteString
      getTrendSideBytes();

  /**
   * <code>string fee = 13;</code>
   */
  String getFee();
  /**
   * <code>string fee = 13;</code>
   */
  com.google.protobuf.ByteString
      getFeeBytes();

  /**
   * <code>.google.protobuf.Timestamp ctime = 14;</code>
   */
  boolean hasCtime();
  /**
   * <code>.google.protobuf.Timestamp ctime = 14;</code>
   */
  com.google.protobuf.Timestamp getCtime();
  /**
   * <code>.google.protobuf.Timestamp ctime = 14;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCtimeOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp mtime = 15;</code>
   */
  boolean hasMtime();
  /**
   * <code>.google.protobuf.Timestamp mtime = 15;</code>
   */
  com.google.protobuf.Timestamp getMtime();
  /**
   * <code>.google.protobuf.Timestamp mtime = 15;</code>
   */
  com.google.protobuf.TimestampOrBuilder getMtimeOrBuilder();
}
