// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CoTradeService.proto

package com.bjs.contract.proto.coTrade;

/**
 * Protobuf type {@code coTrade.CoTradePageRequest}
 */
public  final class CoTradePageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coTrade.CoTradePageRequest)
    CoTradePageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CoTradePageRequest.newBuilder() to construct.
  private CoTradePageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CoTradePageRequest() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CoTradePageRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            page_ = input.readInt32();
            break;
          }
          case 16: {

            size_ = input.readInt32();
            break;
          }
          case 26: {
            CoTradePO.Builder subBuilder = null;
            if (coTradePO_ != null) {
              subBuilder = coTradePO_.toBuilder();
            }
            coTradePO_ = input.readMessage(CoTradePO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(coTradePO_);
              coTradePO_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CoTradeBizServiceProto.internal_static_coTrade_CoTradePageRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CoTradeBizServiceProto.internal_static_coTrade_CoTradePageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CoTradePageRequest.class, Builder.class);
  }

  public static final int PAGE_FIELD_NUMBER = 1;
  private int page_;
  /**
   * <code>int32 page = 1;</code>
   */
  public int getPage() {
    return page_;
  }

  public static final int SIZE_FIELD_NUMBER = 2;
  private int size_;
  /**
   * <code>int32 size = 2;</code>
   */
  public int getSize() {
    return size_;
  }

  public static final int COTRADEPO_FIELD_NUMBER = 3;
  private CoTradePO coTradePO_;
  /**
   * <code>.coTrade.CoTradePO coTradePO = 3;</code>
   */
  public boolean hasCoTradePO() {
    return coTradePO_ != null;
  }
  /**
   * <code>.coTrade.CoTradePO coTradePO = 3;</code>
   */
  public CoTradePO getCoTradePO() {
    return coTradePO_ == null ? CoTradePO.getDefaultInstance() : coTradePO_;
  }
  /**
   * <code>.coTrade.CoTradePO coTradePO = 3;</code>
   */
  public CoTradePOOrBuilder getCoTradePOOrBuilder() {
    return getCoTradePO();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (page_ != 0) {
      output.writeInt32(1, page_);
    }
    if (size_ != 0) {
      output.writeInt32(2, size_);
    }
    if (coTradePO_ != null) {
      output.writeMessage(3, getCoTradePO());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (page_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, page_);
    }
    if (size_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, size_);
    }
    if (coTradePO_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getCoTradePO());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CoTradePageRequest)) {
      return super.equals(obj);
    }
    CoTradePageRequest other = (CoTradePageRequest) obj;

    if (getPage()
        != other.getPage()) return false;
    if (getSize()
        != other.getSize()) return false;
    if (hasCoTradePO() != other.hasCoTradePO()) return false;
    if (hasCoTradePO()) {
      if (!getCoTradePO()
          .equals(other.getCoTradePO())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PAGE_FIELD_NUMBER;
    hash = (53 * hash) + getPage();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize();
    if (hasCoTradePO()) {
      hash = (37 * hash) + COTRADEPO_FIELD_NUMBER;
      hash = (53 * hash) + getCoTradePO().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CoTradePageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CoTradePageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CoTradePageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CoTradePageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CoTradePageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CoTradePageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CoTradePageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CoTradePageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CoTradePageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CoTradePageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CoTradePageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CoTradePageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CoTradePageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code coTrade.CoTradePageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coTrade.CoTradePageRequest)
      CoTradePageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CoTradeBizServiceProto.internal_static_coTrade_CoTradePageRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CoTradeBizServiceProto.internal_static_coTrade_CoTradePageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CoTradePageRequest.class, Builder.class);
    }

    // Construct using com.bjs.contract.proto.coTrade.CoTradePageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      page_ = 0;

      size_ = 0;

      if (coTradePOBuilder_ == null) {
        coTradePO_ = null;
      } else {
        coTradePO_ = null;
        coTradePOBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CoTradeBizServiceProto.internal_static_coTrade_CoTradePageRequest_descriptor;
    }

    @Override
    public CoTradePageRequest getDefaultInstanceForType() {
      return CoTradePageRequest.getDefaultInstance();
    }

    @Override
    public CoTradePageRequest build() {
      CoTradePageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CoTradePageRequest buildPartial() {
      CoTradePageRequest result = new CoTradePageRequest(this);
      result.page_ = page_;
      result.size_ = size_;
      if (coTradePOBuilder_ == null) {
        result.coTradePO_ = coTradePO_;
      } else {
        result.coTradePO_ = coTradePOBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CoTradePageRequest) {
        return mergeFrom((CoTradePageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CoTradePageRequest other) {
      if (other == CoTradePageRequest.getDefaultInstance()) return this;
      if (other.getPage() != 0) {
        setPage(other.getPage());
      }
      if (other.getSize() != 0) {
        setSize(other.getSize());
      }
      if (other.hasCoTradePO()) {
        mergeCoTradePO(other.getCoTradePO());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CoTradePageRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CoTradePageRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int page_ ;
    /**
     * <code>int32 page = 1;</code>
     */
    public int getPage() {
      return page_;
    }
    /**
     * <code>int32 page = 1;</code>
     */
    public Builder setPage(int value) {
      
      page_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 page = 1;</code>
     */
    public Builder clearPage() {
      
      page_ = 0;
      onChanged();
      return this;
    }

    private int size_ ;
    /**
     * <code>int32 size = 2;</code>
     */
    public int getSize() {
      return size_;
    }
    /**
     * <code>int32 size = 2;</code>
     */
    public Builder setSize(int value) {
      
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 size = 2;</code>
     */
    public Builder clearSize() {
      
      size_ = 0;
      onChanged();
      return this;
    }

    private CoTradePO coTradePO_;
    private com.google.protobuf.SingleFieldBuilderV3<
        CoTradePO, CoTradePO.Builder, CoTradePOOrBuilder> coTradePOBuilder_;
    /**
     * <code>.coTrade.CoTradePO coTradePO = 3;</code>
     */
    public boolean hasCoTradePO() {
      return coTradePOBuilder_ != null || coTradePO_ != null;
    }
    /**
     * <code>.coTrade.CoTradePO coTradePO = 3;</code>
     */
    public CoTradePO getCoTradePO() {
      if (coTradePOBuilder_ == null) {
        return coTradePO_ == null ? CoTradePO.getDefaultInstance() : coTradePO_;
      } else {
        return coTradePOBuilder_.getMessage();
      }
    }
    /**
     * <code>.coTrade.CoTradePO coTradePO = 3;</code>
     */
    public Builder setCoTradePO(CoTradePO value) {
      if (coTradePOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        coTradePO_ = value;
        onChanged();
      } else {
        coTradePOBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.coTrade.CoTradePO coTradePO = 3;</code>
     */
    public Builder setCoTradePO(
        CoTradePO.Builder builderForValue) {
      if (coTradePOBuilder_ == null) {
        coTradePO_ = builderForValue.build();
        onChanged();
      } else {
        coTradePOBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.coTrade.CoTradePO coTradePO = 3;</code>
     */
    public Builder mergeCoTradePO(CoTradePO value) {
      if (coTradePOBuilder_ == null) {
        if (coTradePO_ != null) {
          coTradePO_ =
            CoTradePO.newBuilder(coTradePO_).mergeFrom(value).buildPartial();
        } else {
          coTradePO_ = value;
        }
        onChanged();
      } else {
        coTradePOBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.coTrade.CoTradePO coTradePO = 3;</code>
     */
    public Builder clearCoTradePO() {
      if (coTradePOBuilder_ == null) {
        coTradePO_ = null;
        onChanged();
      } else {
        coTradePO_ = null;
        coTradePOBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.coTrade.CoTradePO coTradePO = 3;</code>
     */
    public CoTradePO.Builder getCoTradePOBuilder() {
      
      onChanged();
      return getCoTradePOFieldBuilder().getBuilder();
    }
    /**
     * <code>.coTrade.CoTradePO coTradePO = 3;</code>
     */
    public CoTradePOOrBuilder getCoTradePOOrBuilder() {
      if (coTradePOBuilder_ != null) {
        return coTradePOBuilder_.getMessageOrBuilder();
      } else {
        return coTradePO_ == null ?
            CoTradePO.getDefaultInstance() : coTradePO_;
      }
    }
    /**
     * <code>.coTrade.CoTradePO coTradePO = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        CoTradePO, CoTradePO.Builder, CoTradePOOrBuilder>
        getCoTradePOFieldBuilder() {
      if (coTradePOBuilder_ == null) {
        coTradePOBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            CoTradePO, CoTradePO.Builder, CoTradePOOrBuilder>(
                getCoTradePO(),
                getParentForChildren(),
                isClean());
        coTradePO_ = null;
      }
      return coTradePOBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:coTrade.CoTradePageRequest)
  }

  // @@protoc_insertion_point(class_scope:coTrade.CoTradePageRequest)
  private static final CoTradePageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CoTradePageRequest();
  }

  public static CoTradePageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CoTradePageRequest>
      PARSER = new com.google.protobuf.AbstractParser<CoTradePageRequest>() {
    @Override
    public CoTradePageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CoTradePageRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CoTradePageRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CoTradePageRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public CoTradePageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

