// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CoPositionOrderService.proto

package com.bjs.contract.proto.coPositionOrder;

public interface FundingRateSettleMarginItemPOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coPositionOrder.FundingRateSettleMarginItemPO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 uid = 1;</code>
   */
  long getUid();

  /**
   * <code>string amount = 2;</code>
   */
  String getAmount();
  /**
   * <code>string amount = 2;</code>
   */
  com.google.protobuf.ByteString
      getAmountBytes();
}
